#!/bin/sh
docker run --rm --init -it \
  --user $(id -u) \
  --workdir /src \
  -p 3000:3000 \
  -v $(pwd):/src \
  -e YARN_CACHE_FOLDER=/.yarn \
  -e COMMIT=$(git rev-parse --short=8 HEAD) \
  node:16-slim "$@"
 